### ISSUE TITLE
Add flag feature to automatically use all images as primary rather than doing the whole primary T1w dance and pony show

### ISSUE THREAD

**Issue by dmoracze** [nimh-dsst/dsst-defacing-pipeline#10]
Provide the user with an option to skip the VisualQC of primary scans before defacing. In other words, run it as a one-shot script that identifies primaries, generates mapping file and runs the defacing commands all with one single command.

**Comment by Arshitha** [comment]
Visual Inspection of primary scans is now optional. So, the user now only has to run the one script, `dsst_defacing_wf.py` to deface all the anatomical scans in one shot. The QC failures will have to be dealt in the very end by applying appropriate fixes. The changes have been committed to the `integrate-to-bids` branch. Will tag the PR once I'm ready.
