### ISSUE TITLE
Add an anonymization flag

### ISSUE THREAD

**Issue by Arshitha** [nimh-dsst/dsst-defacing-pipeline#33]
Providing this flag would remove the `AcquisitionDateTime` field in JSON sidecars in the defaced dataset. This could also be extended to remove any other sidecar fields that contain potentially identifying information.

**Comment by dmoracze** [comment]
Would want to make sure other modalities are also taken into account here.

Also fwiw, cubids already has this functionality.

**Comment by Arshitha** [comment]
@dmoracze this has been taken care of in PR#35, thanks!
