### ISSUE TITLE
fsleyes render not working

### ISSUE THREAD

**Issue by Arshitha** [nimh-dsst/dsst-defacing-pipeline#40]
Issue reported here https://github.com/pauldmccarthy/fsleyes/issues/135

**Comment by yarikoptic** [comment]
note: it was addressed upstream and should work in conda-based (not pip-installed) environment. environment.yaml here seems to install it from conda so should be all set afaik

**Comment by Arshitha** [comment]
Just tested it and yes, it's all good now. Thanks!
